name: CI (Android heavy)

on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Comma-separated suites (test,assemble,all)'
        required: false
        default: 'test,assemble'

concurrency:
  group: heavy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK (auto-detect from build files)
        shell: bash
        run: |
          set -euo pipefail
          COMPILE_SDK=$(grep -Rho "compileSdk *[0-9][0-9]" . | tail -n1 | grep -o "[0-9]*")
          BUILD_TOOLS=$(grep -Rho 'buildToolsVersion *"[0-9\.]*"' . | head -n1 | grep -o '[0-9\.]*' || true)
          sdkmanager "platform-tools" "platforms;android-${COMPILE_SDK}"
          if [ -n "${BUILD_TOOLS:-}" ]; then sdkmanager "build-tools;${BUILD_TOOLS}"; fi
          yes | sdkmanager --licenses

      - name: Run selected suites
        shell: bash
        run: |
          set -euo pipefail
          suites="${{ github.event.inputs.suites }}"
          IFS=',' read -ra arr <<< "${suites:-test,assemble}"
          for s in "${arr[@]}"; do
            case "$s" in
              test) ./gradlew --console=plain :feature-exam:test ;;
              assemble) ./gradlew --console=plain assembleDebug ;;
              all) ./gradlew --console=plain test assembleDebug ;;
              *) echo "Unknown suite: $s" && exit 1 ;;
            esac
          done

